const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, 'src', 'locales');

const translations = {
    "hindi": {
        "pageTitle": "संपर्क करें",
        "pageSubtitle": "हमारी टीम से संपर्क करें",
        "emailTitle": "हमें ईमेल करें",
        "emailResponse": "हम आमतौर पर 24 घंटे के भीतर जवाब देते हैं",
        "phoneTitle": "हमें कॉल करें",
        "phoneHours": "सोम-शुक्र सुबह 8 बजे से शाम 5 बजे तक",
        "locationTitle": "हमसे मिलें",
        "locationCity": "जबलपुर",
        "locationState": "मध्य प्रदेश",
        "supportHoursTitle": "सहयोग का समय",
        "supportHoursWeekday": "सोम - शुक्र: सुबह 9 बजे - शाम 6 बजे",
        "supportHoursWeekend": "शनि - रवि: सुबह 10 बजे - दोपहर 2 बजे",
        "formNameLabel": "पूरा नाम",
        "formNamePlaceholder": "जॉन डो",
        "formEmailLabel": "ईमेल पता",
        "formEmailPlaceholder": "john@example.com",
        "formPhoneLabel": "फ़ोन नंबर",
        "formPhonePlaceholder": "+91 83598 90909",
        "formCategoryLabel": "श्रेणी",
        "formSubjectLabel": "विषय",
        "formSubjectPlaceholder": "आपकी समस्या का संक्षिप्त विवरण",
        "formMessageLabel": "संदेश",
        "formMessagePlaceholder": "हम आपकी कैसे मदद कर सकते हैं?",
        "formSubmitButton": "संदेश भेजें",
        "formSubmitting": "भेज रहा है...",
        "faqTitle": "अक्सर पूछे जाने वाले प्रश्न",
        "validationNameRequired": "नाम आवश्यक है",
        "validationEmailRequired": "ईमेल आवश्यक है",
        "validationEmailInvalid": "अमान्य ईमेल पता",
        "validationSubjectRequired": "विषय आवश्यक है",
        "validationMessageRequired": "संदेश आवश्यक है",
        "validationMessageTooShort": "संदेश कम से कम 10 अक्षरों का होना चाहिए",
        "toastError": "कृपया फ़ॉर्म में त्रुटियों को ठीक करें",
        "toastSuccess": "संदेश सफलतापूर्वक भेजा गया!",
        "toastFailed": "संदेश भेजने में विफल",
        "categories": {
            "general": "सामान्य पूछताछ",
            "technical": "तकनीकी सहायता",
            "bug": "बग रिपोर्ट करें",
            "feedback": "सुझाव",
            "partnership": "साझेदारी"
        }
    },
    "bengali": {
        "pageTitle": "যোগাযোগ করুন",
        "pageSubtitle": "আমাদের দলের সাথে যোগাযোগ করুন",
        "emailTitle": "আমাদের ইমেল করুন",
        "emailResponse": "আমরা সাধারণত ২৪ ঘন্টার মধ্যে উত্তর দিই",
        "phoneTitle": "আমাদের কল করুন",
        "phoneHours": "সোম-শুক্র সকাল ৮টা থেকে বিকাল ৫টা",
        "locationTitle": "আমাদের সাথে দেখা করুন",
        "locationCity": "জবলপুর",
        "locationState": "মধ্য প্রদেশ",
        "supportHoursTitle": "সহায়তার সময়",
        "supportHoursWeekday": "সোম - শুক্র: সকাল ৯টা - সন্ধ্যা ৬টা",
        "supportHoursWeekend": "শনি - রবি: সকাল ১০টা - দুপুর ২টা",
        "formNameLabel": "পুরো নাম",
        "formNamePlaceholder": "জন ডো",
        "formEmailLabel": "ইমেল ঠিকানা",
        "formEmailPlaceholder": "john@example.com",
        "formPhoneLabel": "ফোন নম্বর",
        "formPhonePlaceholder": "+91 83598 90909",
        "formCategoryLabel": "বিভাগ",
        "formSubjectLabel": "বিষয়",
        "formSubjectPlaceholder": "আপনার সমস্যার সংক্ষিপ্ত বিবরণ",
        "formMessageLabel": "বার্তা",
        "formMessagePlaceholder": "আমরা কিভাবে আপনাকে সাহায্য করতে পারি?",
        "formSubmitButton": "বার্তা পাঠান",
        "formSubmitting": "পাঠানো হচ্ছে...",
        "faqTitle": "সচরাচর জিজ্ঞাসিত প্রশ্ন",
        "validationNameRequired": "নাম প্রয়োজন",
        "validationEmailRequired": "ইমেল প্রয়োজন",
        "validationEmailInvalid": "অবৈধ ইমেল ঠিকানা",
        "validationSubjectRequired": "বিষয় প্রয়োজন",
        "validationMessageRequired": "বার্তা প্রয়োজন",
        "validationMessageTooShort": "বার্তা অন্তত ১০ অক্ষরের হতে হবে",
        "toastError": "ফর্মের ত্রুটিগুলি সংশোধন করুন",
        "toastSuccess": "বার্তা সফলভাবে পাঠানো হয়েছে!",
        "toastFailed": "বার্তা পাঠাতে ব্যর্থ",
        "categories": {
            "general": "সাধারণ অনুসন্ধান",
            "technical": "প্রযুক্তিগত সহায়তা",
            "bug": "বাগ রিপোর্ট করুন",
            "feedback": "প্রতিক্রিয়া",
            "partnership": "অংশীদারিত্ব"
        }
    },
    "tamil": {
        "pageTitle": "தொடர்பு கொள்ள",
        "pageSubtitle": "எங்கள் குழுவுடன் இணையுங்கள்",
        "emailTitle": "எங்களுக்கு மின்னஞ்சல் அனுப்புங்கள்",
        "emailResponse": "நாங்கள் பொதுவாக 24 மணி நேரத்திற்குள் பதிலளிப்போம்",
        "phoneTitle": "எங்களை அழைக்கவும்",
        "phoneHours": "திங்கள்-வெள்ளி காலை 8 மணி முதல் மாலை 5 மணி வரை",
        "locationTitle": "எங்களை பார்வையிடவும்",
        "locationCity": "ஜபல்பூர்",
        "locationState": "மத்தியப் பிரதேசம்",
        "supportHoursTitle": "ஆதரவு நேரங்கள்",
        "supportHoursWeekday": "திங்கள் - வெள்ளி: காலை 9 - மாலை 6",
        "supportHoursWeekend": "சனி - ஞாயிறு: காலை 10 - மதியம் 2",
        "formNameLabel": "முழு பெயர்",
        "formNamePlaceholder": "ஜான் டோ",
        "formEmailLabel": "மின்னஞ்சல் முகவரி",
        "formEmailPlaceholder": "john@example.com",
        "formPhoneLabel": "தொலைபேசி எண்",
        "formPhonePlaceholder": "+91 83598 90909",
        "formCategoryLabel": "வகை",
        "formSubjectLabel": "பொருள்",
        "formSubjectPlaceholder": "உங்கள் பிரச்சனை பற்றிய சுருக்கம்",
        "formMessageLabel": "செய்தி",
        "formMessagePlaceholder": "நாங்கள் உங்களுக்கு எப்படி உதவ முடியும்?",
        "formSubmitButton": "செய்தி அனுப்பவும்",
        "formSubmitting": "அனுப்பப்படுகிறது...",
        "faqTitle": "அடிக்கடி கேட்கப்படும் கேள்விகள்",
        "validationNameRequired": "பெயர் அவசியம்",
        "validationEmailRequired": "மின்னஞ்சல் அவசியம்",
        "validationEmailInvalid": "செல்லாத மின்னஞ்சல் முகவரி",
        "validationSubjectRequired": "பொருள் அவசியம்",
        "validationMessageRequired": "செய்தி அவசியம்",
        "validationMessageTooShort": "செய்தி குறைந்தது 10 எழுத்துக்கள் இருக்க வேண்டும்",
        "toastError": "படிவத்தில் உள்ள பிழைகளை சரிசெய்யவும்",
        "toastSuccess": "செய்தி வெற்றிகரமாக அனுப்பப்பட்டது!",
        "toastFailed": "செய்தி அனுப்ப முடியவில்லை",
        "categories": {
            "general": "பொது விசாரணை",
            "technical": "தொழில்நுட்ப ஆதரவு",
            "bug": "பிழையைப் புகாரளிக்கவும்",
            "feedback": "கருத்து",
            "partnership": "கூட்டாண்மை"
        }
    },
    "telugu": {
        "pageTitle": "మమ్మల్ని సంప్రదించండి",
        "pageSubtitle": "మా బృందంతో కనెక్ట్ అవ్వండి",
        "emailTitle": "మాకు ఇమెయిల్ చేయండి",
        "emailResponse": "మేము సాధారణంగా 24 గంటల్లో స్పందిస్తాము",
        "phoneTitle": "మాకు కాల్ చేయండి",
        "phoneHours": "సోమ-శుక్ర ఉదయం 8 నుండి సా 5 వరకు",
        "locationTitle": "మమ్మల్ని సందర్శించండి",
        "locationCity": "జబల్పూర్",
        "locationState": "మధ్యప్రదేశ్",
        "supportHoursTitle": "సహాయ సమయాలు",
        "supportHoursWeekday": "సోమ - శుక్ర: ఉ 9 - సా 6",
        "supportHoursWeekend": "శని - ఆది: ఉ 10 - మ 2",
        "formNameLabel": "పూర్తి పేరు",
        "formNamePlaceholder": "జాన్ డో",
        "formEmailLabel": "ఇమెయిల్ చిరునామా",
        "formEmailPlaceholder": "john@example.com",
        "formPhoneLabel": "ఫోన్ నంబర్",
        "formPhonePlaceholder": "+91 83598 90909",
        "formCategoryLabel": "వర్గం",
        "formSubjectLabel": "విషయం",
        "formSubjectPlaceholder": "మీ సమస్య సారాంశం",
        "formMessageLabel": "సందేశం",
        "formMessagePlaceholder": "మేము మీకు ఎలా సహాయపడగలము?",
        "formSubmitButton": "సందేశం పంపండి",
        "formSubmitting": "పంపుతోంది...",
        "faqTitle": "తరచుగా అడిగే ప్రశ్నలు",
        "validationNameRequired": "పేరు అవసరం",
        "validationEmailRequired": "ఇమెయిల్ అవసరం",
        "validationEmailInvalid": "చెల్లని ఇమెయిల్ చిరునామా",
        "validationSubjectRequired": "విషయం అవసరం",
        "validationMessageRequired": "సందేశం అవసరం",
        "validationMessageTooShort": "సందేశం కనీసం 10 అక్షరాలు ఉండాలి",
        "toastError": "దయచేసి ఫారమ్‌లోని లోపాలను సరిచేయండి",
        "toastSuccess": "సందేశం విజయవంతంగా పంపబడింది!",
        "toastFailed": "సందేశం పంపడం విఫలమైంది",
        "categories": {
            "general": "సాధారణ విచారణ",
            "technical": "సాంకేతిక మద్దతు",
            "bug": "బగ్ రిపోర్ట్ చేయండి",
            "feedback": "అభిప్రాయం",
            "partnership": "భాగస్వామ్యం"
        }
    },
    "marathi": {
        "pageTitle": "संपर्क साधा",
        "pageSubtitle": "आमच्या टीमशी संपर्क साधा",
        "emailTitle": "आम्हाला ईमेल करा",
        "emailResponse": "आम्ही साधारणपणे २४ तासात उत्तर देतो",
        "phoneTitle": "आम्हाला कॉल करा",
        "phoneHours": "सोम-शुक्र सकाळी ८ ते सायं ५",
        "locationTitle": "आम्हाला भेट द्या",
        "locationCity": "जबलपूर",
        "locationState": "मध्य प्रदेश",
        "supportHoursTitle": "सपोर्ट वेळ",
        "supportHoursWeekday": "सोम - शुक्र: स ९ - सा ६",
        "supportHoursWeekend": "शनी - रवी: स १० - दु २",
        "formNameLabel": "पूर्ण नाव",
        "formNamePlaceholder": "जॉन डो",
        "formEmailLabel": "ईमेल पत्ता",
        "formEmailPlaceholder": "john@example.com",
        "formPhoneLabel": "फोन नंबर",
        "formPhonePlaceholder": "+91 83598 90909",
        "formCategoryLabel": "श्रेणी",
        "formSubjectLabel": "विषय",
        "formSubjectPlaceholder": "तुमच्या समस्येचा सारांश",
        "formMessageLabel": "संदेश",
        "formMessagePlaceholder": "आम्ही तुम्हाला कशी मदत करू शकतो?",
        "formSubmitButton": "संदेश पाठवा",
        "formSubmitting": "पाठवत आहे...",
        "faqTitle": "वारंवार विचारले जाणारे प्रश्न",
        "validationNameRequired": "नाव आवश्यक आहे",
        "validationEmailRequired": "ईमेल आवश्यक आहे",
        "validationEmailInvalid": "अवैध ईमेल पत्ता",
        "validationSubjectRequired": "विषय आवश्यक आहे",
        "validationMessageRequired": "संदेश आवश्यक आहे",
        "validationMessageTooShort": "संदेश किमान १० अक्षरांचा असावा",
        "toastError": "कृपया फॉर्ममधील त्रुटी सुधारा",
        "toastSuccess": "संदेश यशस्वीरित्या पाठविला!",
        "toastFailed": "संदेश पाठविण्यात अयशस्वी",
        "categories": {
            "general": "सामान्य चौकशी",
            "technical": "तांत्रिक आधार",
            "bug": "बग रिपोर्ट करा",
            "feedback": "अभिप्राय",
            "partnership": "भागीदारी"
        }
    },
    "gujarati": {
        "pageTitle": "અમારો સંપર્ક કરો",
        "pageSubtitle": "અમારી ટીમ સાથે જોડાઓ",
        "emailTitle": "અમને ઇમેઇલ કરો",
        "emailResponse": "અમે સામાન્ય રીતે ૨૪ કલાકમાં જવાબ આપીએ છીએ",
        "phoneTitle": "અમને કૉલ કરો",
        "phoneHours": "સોમ-શુક્ર સવારે ૮ થી સાંજે ૫",
        "locationTitle": "અમારી મુલાકાત લો",
        "locationCity": "જબલપુર",
        "locationState": "મધ્ય પ્રદેશ",
        "supportHoursTitle": "સપોર્ટ સમય",
        "supportHoursWeekday": "સોમ - શુક્ર: સવારે ૯ - સાંજે ૬",
        "supportHoursWeekend": "શનિ - રવિ: સવારે ૧૦ - બપોરે ૨",
        "formNameLabel": "પૂરું નામ",
        "formNamePlaceholder": "જ્હોન ડો",
        "formEmailLabel": "ઇમેઇલ સરનામું",
        "formEmailPlaceholder": "john@example.com",
        "formPhoneLabel": "ફોન નંબર",
        "formPhonePlaceholder": "+91 83598 90909",
        "formCategoryLabel": "શ્રેણી",
        "formSubjectLabel": "વિષય",
        "formSubjectPlaceholder": "તમારી સમસ્યાનો સારાંશ",
        "formMessageLabel": "સંદેશ",
        "formMessagePlaceholder": "અમે તમને કેવી રીતે મદદ કરી શકીએ?",
        "formSubmitButton": "સંદેશ મોકલો",
        "formSubmitting": "મોકલી રહ્યું છે...",
        "faqTitle": "વારંવાર પૂછાતા પ્રશ્નો",
        "validationNameRequired": "નામ આવશ્યક છે",
        "validationEmailRequired": "ઇમેઇલ આવશ્યક છે",
        "validationEmailInvalid": "અમાન્ય ઇમેઇલ સરનામું",
        "validationSubjectRequired": "વિષય આવશ્યક છે",
        "validationMessageRequired": "સંદેશ આવશ્યક છે",
        "validationMessageTooShort": "સંદેશ ઓછામાં ઓછા ૧૦ અક્ષરોનો હોવો જોઈએ",
        "toastError": "કૃપા કરીને ફોર્મમાં ભૂલો સુધારો",
        "toastSuccess": "સંદેશ સફળતાપૂર્વક મોકલ્યો!",
        "toastFailed": "સંદેશ મોકલવામાં નિષ્ફળ",
        "categories": {
            "general": "સામાન્ય પૂછપરછ",
            "technical": "તકનીકી સપોર્ટ",
            "bug": "બગ રિપોર્ટ કરો",
            "feedback": "પ્રતિસાદ",
            "partnership": "ભાગીદારી"
        }
    },
    "french": {
        "pageTitle": "Contactez-nous",
        "pageSubtitle": "Entrez en contact avec notre équipe",
        "emailTitle": "Envoyez-nous un email",
        "emailResponse": "Nous répondons généralement sous 24 heures",
        "phoneTitle": "Appelez-nous",
        "phoneHours": "Lun-Ven de 8h à 17h",
        "locationTitle": "Rendez-nous visite",
        "locationCity": "Jabalpur",
        "locationState": "Madhya Pradesh",
        "supportHoursTitle": "Heures d'assistance",
        "supportHoursWeekday": "Lun - Ven : 9h00 - 18h00",
        "supportHoursWeekend": "Sam - Dim : 10h00 - 14h00",
        "formNameLabel": "NOM COMPLET",
        "formNamePlaceholder": "Jean Dupont",
        "formEmailLabel": "ADRESSE EMAIL",
        "formEmailPlaceholder": "jean@exemple.com",
        "formPhoneLabel": "NUMÉRO DE TÉLÉPHONE",
        "formPhonePlaceholder": "+33 6 12 34 56 78",
        "formCategoryLabel": "CATÉGORIE",
        "formSubjectLabel": "SUJET",
        "formSubjectPlaceholder": "Bref résumé de votre problème",
        "formMessageLabel": "MESSAGE",
        "formMessagePlaceholder": "Comment pouvons-nous vous aider ?",
        "formSubmitButton": "Envoyer le message",
        "formSubmitting": "Envoi...",
        "faqTitle": "Foire aux questions",
        "validationNameRequired": "Le nom est requis",
        "validationEmailRequired": "L'email est requis",
        "validationEmailInvalid": "Adresse email invalide",
        "validationSubjectRequired": "Le sujet est requis",
        "validationMessageRequired": "Le message est requis",
        "validationMessageTooShort": "Le message doit contenir au moins 10 caractères",
        "toastError": "Veuillez corriger les erreurs dans le formulaire",
        "toastSuccess": "Message envoyé avec succès !",
        "toastFailed": "Échec de l'envoi du message",
        "categories": {
            "general": "Demande générale",
            "technical": "Support technique",
            "bug": "Signaler un bug",
            "feedback": "Commentaires",
            "partnership": "Partenariat"
        }
    },
    "spanish": {
        "pageTitle": "Contáctenos",
        "pageSubtitle": "Póngase en contacto con nuestro equipo",
        "emailTitle": "Envíenos un correo",
        "emailResponse": "Solemos responder en 24 horas",
        "phoneTitle": "Llámenos",
        "phoneHours": "Lun-Vie de 8am a 5pm",
        "locationTitle": "Visítenos",
        "locationCity": "Jabalpur",
        "locationState": "Madhya Pradesh",
        "supportHoursTitle": "Horario de soporte",
        "supportHoursWeekday": "Lun - Vie: 9AM - 6PM",
        "supportHoursWeekend": "Sáb - Dom: 10AM - 2PM",
        "formNameLabel": "NOMBRE COMPLETO",
        "formNamePlaceholder": "Juan Pérez",
        "formEmailLabel": "CORREO ELECTRÓNICO",
        "formEmailPlaceholder": "juan@ejemplo.com",
        "formPhoneLabel": "NÚMERO DE TELÉFONO",
        "formPhonePlaceholder": "+34 612 345 678",
        "formCategoryLabel": "CATEGORÍA",
        "formSubjectLabel": "ASUNTO",
        "formSubjectPlaceholder": "Breve resumen de su problema",
        "formMessageLabel": "MENSAJE",
        "formMessagePlaceholder": "¿Cómo podemos ayudarle?",
        "formSubmitButton": "Enviar mensaje",
        "formSubmitting": "Enviando...",
        "faqTitle": "Preguntas frecuentes",
        "validationNameRequired": "El nombre es obligatorio",
        "validationEmailRequired": "El correo es obligatorio",
        "validationEmailInvalid": "Correo inválido",
        "validationSubjectRequired": "El asunto es obligatorio",
        "validationMessageRequired": "El mensaje es obligatorio",
        "validationMessageTooShort": "El mensaje debe tener al menos 10 caracteres",
        "toastError": "Por favor corrija los errores en el formulario",
        "toastSuccess": "¡Mensaje enviado con éxito!",
        "toastFailed": "Error al enviar el mensaje",
        "categories": {
            "general": "Consulta general",
            "technical": "Soporte técnico",
            "bug": "Reportar un error",
            "feedback": "Comentarios",
            "partnership": "Asociación"
        }
    },
    "arabic": {
        "pageTitle": "اتصل بنا",
        "pageSubtitle": "تواصل مع فريقنا",
        "emailTitle": "راسلنا عبر البريد الإلكتروني",
        "emailResponse": "نرد عادة في غضون 24 ساعة",
        "phoneTitle": "اتصل بنا",
        "phoneHours": "من الاثنين إلى الجمعة من 8 صباحًا حتى 5 مساءً",
        "locationTitle": "قم بزيارتنا",
        "locationCity": "جبلبور",
        "locationState": "ماديا براديش",
        "supportHoursTitle": "ساعات الدعم",
        "supportHoursWeekday": "الإثنين - الجمعة: 9 صباحًا - 6 مساءً",
        "supportHoursWeekend": "السبت - الأحد: 10 صباحًا - 2 مساءً",
        "formNameLabel": "الاسم الكامل",
        "formNamePlaceholder": "أحمد محمد",
        "formEmailLabel": "عنوان البريد الإلكتروني",
        "formEmailPlaceholder": "ahmed@example.com",
        "formPhoneLabel": "رقم الهاتف",
        "formPhonePlaceholder": "+966 50 123 4567",
        "formCategoryLabel": "الفئة",
        "formSubjectLabel": "الموضوع",
        "formSubjectPlaceholder": "ملخص موجز لمشكلتك",
        "formMessageLabel": "الرسالة",
        "formMessagePlaceholder": "كيف يمكننا مساعدتك؟",
        "formSubmitButton": "إرسال الرسالة",
        "formSubmitting": "جاري الإرسال...",
        "faqTitle": "الأسئلة الشائعة",
        "validationNameRequired": "الاسم مطلوب",
        "validationEmailRequired": "البريد الإلكتروني مطلوب",
        "validationEmailInvalid": "عنوان بريد إلكتروني غير صالح",
        "validationSubjectRequired": "الموضوع مطلوب",
        "validationMessageRequired": "الرسالة مطلوبة",
        "validationMessageTooShort": "يجب أن تكون الرسالة 10 أحرف على الأقل",
        "toastError": "يرجى تصحيح الأخطاء في النموذج",
        "toastSuccess": "تم إرسال الرسالة بنجاح!",
        "toastFailed": "فشل إرسال الرسالة",
        "categories": {
            "general": "استفسار عام",
            "technical": "دعم فني",
            "bug": "الإبلاغ عن خطأ",
            "feedback": "تعليقات",
            "partnership": "شراكة"
        }
    }
};

Object.keys(translations).forEach(lang => {
    const filePath = path.join(localesDir, `${lang}.json`);
    if (fs.existsSync(filePath)) {
        try {
            const content = JSON.parse(fs.readFileSync(filePath, 'utf8'));
            const tx = translations[lang];

            // Ensure landing object exists
            if (!content.landing) content.landing = {};

            // Apply Contact Us translations under landing.contactUs
            content.landing.contactUs = {
                ...content.landing.contactUs,
                ...tx
            };

            // Remove legacy/top-level contactUs if it exists to avoid confusion (optional, but cleaner)
            // if (content.contactUs) delete content.contactUs; // Decided to keep it just in case logic uses it elsewhere

            // Also keep top-level contactUs updated just in case other components use it
            if (!content.contactUs) content.contactUs = {};
            Object.assign(content.contactUs, tx);

            fs.writeFileSync(filePath, JSON.stringify(content, null, 4));
            console.log(`Updated contactUs in ${lang}.json`);
        } catch (e) {
            console.error(`Error updating ${lang}.json`, e);
        }
    }
});
